version: "3.7"

services:
  deno-rest-api-example:
    container_name: deno-rest-api-example
    restart: always
    init: true
    build: ./
    ports:
      - ${SERVER_PORT:-8080}:${SERVER_PORT:-8080}
    depends_on:
      - deno-rest-api-example-mongodb
    links:
      - deno-rest-api-example-mongodb
    env_file:
      - ./.env
    networks:
      - deno-rest-api-example-network

  deno-rest-api-example-mongodb:
    container_name: deno-rest-api-example-mongodb
    restart: always
    init: true
    image: mongo:3.4
    ports:
      - ${DATABASE_PORT:-27017}:${DATABASE_PORT:-27017}
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DATABASE_USERNAME:-root}
      - MONGO_INITDB_ROOT_PASSWORD=${DATABASE_PASSWORD:-pass}
    env_file:
      - ./.env
    networks:
      - deno-rest-api-example-network

networks:
  deno-rest-api-example-network:
    driver: bridge
